### ISSUE TITLE
Highlight teams that need support

### ISSUE THREAD

**Issue by kfklein15** [nataliiazab/good-pr#171]
AS A Programme Manager / Volunteer
I WANT to visually identify which teams need support during Final Projects.
SO THAT I can focus my effort.

**Acceptance criteria**

**Scenario: border and icon of team falling behind**
GIVEN I am on the Good PR Dashboard
AND I can see all teams
WHEN I a team is falling behind on the PR calculation
THEN I want that team to have a yellow boarder
AND I want to see a yellow triangle as per Figma

![Image](https://github.com/nataliiazab/good-pr/assets/80272258/8a1f4772-5754-438b-aa38-2324a10caea2)

![Image](https://github.com/nataliiazab/good-pr/assets/80272258/30815e62-3ba5-4e28-ae44-4055cfb605a0)

**Scenario: teams on track should not have any design change**
GIVEN I am on the Good PR Dashboard
AND I can see all teams
WHEN I a team is on track on the PR calculation
THEN I should see them without any highlight.

![Image](https://github.com/nataliiazab/good-pr/assets/80272258/da680c57-8431-4e3c-923c-e64dbd99749b)

**Comment by momahboobian** [comment]
- [ ] Implenent the FilterIcon
- [ ] Create condition for the DropShadow
At the moment the intial value has been set to "false"

// GroupPage
` <TeamCard
            key={group.id}
            group={group}
          groupStatus={false}
          />`
// TeamCard
`{groupStatus === true && <AlertIcon tooltipId={tooltipIconId} />}
`

![Image](https://github.com/nataliiazab/good-pr/assets/17272675/f0e06e66-0e56-498d-bdf9-fe96867ba6f3)


when condtion meet the shadow and alert will display
` groupStatus={true}`
![Image](https://github.com/nataliiazab/good-pr/assets/17272675/f897efae-1c7a-4658-bcfb-3f7223eb0096)
