### ISSUE TITLE
Filter teams that need support

### ISSUE THREAD

**Issue by kfklein15** [nataliiazab/good-pr#172]
AS a Programm Manager OR Volunteer
I WANT to be able to filter the teams that need support
SO THAT I can focus my attention no the right teams.

**Acceptance criteria:**

**Scenario: filter teams that need help**
GIVEN I am on the Good PR Dashboard
AND I can see <'allTeams'> teams
WHEN I filter only teams that need help
THEN I can only see <'helpTeam'> team(s).

allTeams | helpTeams
-- | --
6 | 1
6 | 3
6 | 6
6 | 0

**Comment by momahboobian** [comment]
- [ ] Implementing the FilterToggle Fucntionality
- [ ] Altering the GroupPage to behave based on Filter on/off

When filter off display all the teams
![Image](https://github.com/nataliiazab/good-pr/assets/17272675/a1507173-88bf-4550-814f-89bf7b094903)


When filter is On only display the team nees help
![Image](https://github.com/nataliiazab/good-pr/assets/17272675/3ddf075a-12be-419a-9ef9-5000f6e77d11)
