### ISSUE TITLE
Json File

### ISSUE THREAD

**Issue by LorenaCapraru** [nataliiazab/good-pr#6]
Create a **json** file which contains all the data needed for the following design:
As a guide don't forget:

- [x] repo name
- [x] number of contributors
- [x] Date of the last PR issued per team
- [x] total number of tickets issued
- [ ] number of tasks done
- [ ] number of tasks in progress
- [x] contributors array:

> - [ ] each contributor's name
> - [ ] gitHub avatar url for each contributor
> - [ ] each contributor's number of PR's

- [x] tickets array:

> - [ ] assignee
> - [ ] time when its issued
> - [ ] title of the issue
> - [ ] status

**_It's just a guideline, but feel free to create it the way you want just to contain all the info needed to render data for the dashboard._**

![Image](https://github.com/nataliiazab/good-pr/assets/108892538/6597def4-bc98-43c1-a0d2-c15755496e0f)

**Comment by momahboobian** [comment]
@LorenaCapraru
We would be able to access number of the issue but can not access the number of tasks done without auth
